-- MySQL Script generated by MySQL Workbench
-- 06/26/19 18:45:59
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Servicos` (
  `idServicos` INT NOT NULL auto_increment,
  `plantao` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idServicos`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Prestador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Prestador` (
  `idPrestador` INT NOT NULL auto_increment,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` numeric(11) NOT NULL UNIQUE,
  `coren` INT(45) NOT NULL,
  `cel` varchar(45) nOT NULL,
  `status` TINYINT(1) NOT NULL,
  `data` DATETIME NOT NULL,
  `Historico_idHistorico` INT NULL,
  `Historico_Solicitacao_idSolicitacao` INT NULL,
  PRIMARY KEY (`idPrestador`),
  INDEX `fk_Prestador_Historico1_idx` (`Historico_idHistorico` ASC, `Historico_Solicitacao_idSolicitacao` ASC),
  CONSTRAINT `fk_Prestador_Historico1`
    FOREIGN KEY (`Historico_idHistorico` , `Historico_Solicitacao_idSolicitacao`)
    REFERENCES `mydb`.`Historico` (`idHistorico` , `Solicitacao_idSolicitacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Solicitacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Solicitacao` (
  `idSolicitacao` INT NOT NULL auto_increment,
  `Client_idcliente` INT NOT NULL,
  `Servicos_idServicos` INT NOT NULL,
  `Prestador_idPrestador` INT NOT NULL,
  `data` DATE NOT NULL,
  PRIMARY KEY (`idSolicitacao`, `Client_idcliente`, `Servicos_idServicos`, `Prestador_idPrestador`),
  INDEX `fk_Client_has_Servicos_Servicos1_idx` (`Servicos_idServicos` ASC),
  INDEX `fk_Client_has_Servicos_Client_idx` (`Client_idcliente` ASC),
  INDEX `fk_Solicitacao_Prestador1_idx` (`Prestador_idPrestador` ASC),
  CONSTRAINT `fk_Client_has_Servicos_Client`
    FOREIGN KEY (`Client_idcliente`)
    REFERENCES `mydb`.`Cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Client_has_Servicos_Servicos1`
    FOREIGN KEY (`Servicos_idServicos`)
    REFERENCES `mydb`.`Servicos` (`idServicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Solicitacao_Prestador1`
    FOREIGN KEY (`Prestador_idPrestador`)
    REFERENCES `mydb`.`Prestador` (`idPrestador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Historico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Historico` (
  `idHistorico` INT NOT NULL auto_increment,
  `Solicitacao_idSolicitacao` INT NOT NULL,
  `recomend` VARCHAR(45) NULL,
  `obs` VARCHAR(45) NULL,
  PRIMARY KEY (`idHistorico`, `Solicitacao_idSolicitacao`),
  INDEX `fk_Historico_Solicitacao1_idx` (`Solicitacao_idSolicitacao` ASC),
  CONSTRAINT `fk_Historico_Solicitacao1`
    FOREIGN KEY (`Solicitacao_idSolicitacao`)
    REFERENCES `mydb`.`Solicitacao` (`idSolicitacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idcliente` INT NOT NULL auto_increment,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` numeric(11) NOT NULL unique,
  `cel` varchar(45) NOT NULL,
  `senha` VARCHAR(32) NOT NULL,
  `data` DATETIME NOT NULL,
  `Historico_idHistorico` INT NULL,
  `Historico_Solicitacao_idSolicitacao` INT NULL,
  PRIMARY KEY (`idcliente`),
  INDEX `fk_Cliente_Historico1_idx` (`Historico_idHistorico` ASC, `Historico_Solicitacao_idSolicitacao` ASC),
  CONSTRAINT `fk_Cliente_Historico1`
    FOREIGN KEY (`Historico_idHistorico` , `Historico_Solicitacao_idSolicitacao`)
    REFERENCES `mydb`.`Historico` (`idHistorico` , `Solicitacao_idSolicitacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
